font=RobotoMono Nerd Font:size=10
prompt="// "
icons-enabled=yes
match-mode=fzf
terminal=alacritty -e
lines=10
horizontal-pad=20
vertical-pad=14
inner-pad=14
enable-mouse=yes

line-height=24

layer=overlay

# Color
include=~/.config/fuzzel/themes/catppuccin-latte/sky.ini

[border]
width=4
radius=16
selection-radius=16

[dmenu]
mode=text
exit-immediately-if-empty=no
