#! /bin/sh

chosen=$(printf "  Lock\n󰗽  Log Out\n  Suspend\n  Hibernate\n  Restart\n  Power Off" | fuzzel --dmenu --lines 6)

lock="swaylock --daemonize --indicator-caps-lock --show-failed-attempts"

case "$chosen" in
	"  Lock") $lock;;
	"󰗽  Log Out") hyprctl dispatch exit ;;
	"  Suspend") $lock & systemctl suspend-then-hibernate ;;
	"  Hibernate") systemctl hibernate ;;
	"  Restart") reboot ;;
	"  Power Off") poweroff ;;
	*) exit 1 ;;
esac
