font=RobotoMono Nerd Font:size=12
prompt="// "
icons-enabled=yes
match-mode=fzf
terminal=alacritty -e
horizontal-pad=20
vertical-pad=14
enable-mouse=yes

# Color
include=~/.config/fuzzel/themes/catppuccin-latte/sky.ini

[border]
width=4
radius=16

[dmenu]
mode=text
exit-immediately-if-empty=no
