# Theming
set -g @catppuccin_flavor 'latte'
set -g @catppuccin_window_current_number_color "#{@thm_sky}"
set -g @catppuccin_window_status_style "basic" # Makes windows rectangular
set -g @catppuccin_status_left_separator "█"   # Makes modules rectangular
set -g @catppuccin_window_text " // #{b:pane_current_path}"
set -g @catppuccin_window_current_text " #{pane_current_path}"
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_session}"

# Allow mouse to click windows and scroll buffer
set -g mouse on

# Open panes/windows in current directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# Vim bindings
set-option -g status-keys vi
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Miscellaneous options
set -g history-limit 200000
set -g display-time 4000
set -sg escape-time 0
set -g focus-events on
setw -g aggressive-resize on
set -g default-terminal "tmux-256color"
