wallpaper {
    monitor = DP-2
    path = ~/.config/waypaper/endfield1.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/.config/waypaper/endfield1.jpg
    fit_mode = cover
}
