import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[window]
padding = { x = 5, y = 5 }
dynamic_padding = true
opacity = 0.8

[font]
normal = { family = "FiraMono Nerd Font Mono", style = "Regular"}

[keyboard]
bindings = [
   { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]
