[general]
import = ["./catppuccin-latte.toml"]

[window]
padding = { x = 5, y = 5 }
dynamic_padding = true
opacity = 0.8

[font]
normal = { family = "RobotoMono Nerd Font", style = "Medium"}

[keyboard]
bindings = [
   { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]
